-- AlterTable
ALTER TABLE `approval` ADD COLUMN `approverRole` ENUM('ADMIN', 'SALES', 'MANAGER', 'FINANCE_MANAGER', 'CUSTOMER') NOT NULL DEFAULT 'MANAGER';

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('ADMIN', 'SALES', 'MANAGER', 'FINANCE_MANAGER', 'CUSTOMER') NOT NULL;
